/**
 * @file nist_kat_data.h
 * @brief Declarations for the NIST SP 800-22 known-answer-test data
 *
 * The definitions live in nist_kat_data.c, which is GENERATED by
 * tools/gen_kat_golden.py from an sts-2.1.2 reference run. See that
 * script for provenance.
 *
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2026 IPRO Technology Co., Ltd.
 */

#ifndef NIST_KAT_DATA_H
#define NIST_KAT_DATA_H

#include <stdint.h>

/** Expected result for one suite entry (suite order, 16 entries) */
typedef struct {
    const char *name;       /**< Test name (matches suite result order) */
    double      p1;         /**< Expected primary P-value; <0 = see split constants */
    double      p2;         /**< Expected secondary P-value (Serial); <0 = none */
    double      tol;        /**< Comparison tolerance (absolute) */
} nist_kat_expect_t;

/** Number of bits in the KAT stream (2^20) */
extern const uint32_t nist_kat_n_bits;

/** First 2^20 bits of e's binary expansion, packed MSB-first per byte */
extern const uint8_t nist_kat_e_bits[131072];

/** Golden values in suite order; Non-overlapping entry has p1 < 0 */
extern const nist_kat_expect_t nist_kat_expect[16];

/** Non-overlapping golden min P-value over the official 148 templates */
extern const double nist_kat_nonoverlap_full_minp;

/** Non-overlapping golden min P-value over the quick-mode 10 templates */
extern const double nist_kat_nonoverlap_quick_minp;

#endif /* NIST_KAT_DATA_H */
