/*
 * Copyright (c) 2026 IntelPro Technology Co., Ltd.
 * All rights reserved.
 *
 * This software and associated documentation files (the "Software") are
 * proprietary and confidential to IntelPro Technology Co., Ltd..
 *
 * Access to and use of this Software is limited exclusively to authorized 
 * customers and partners of IntelPro Technology Co., Ltd. who have entered into a 
 * valid license or non-disclosure agreement.
 *
 * Unauthorized copying, modification, distribution, or reverse engineering 
 * of this Software, via any medium, is strictly prohibited without 
 * prior written permission from IntelPro Technology Co., Ltd..
 *
 * SPDX-License-Identifier: Proprietary
 */

/*
 * pricetag_render — composite a dynamic sale-price string onto one of
 * the pre-baked product templates and push the result to the panel.
 *
 * The templates live in flash (templates.h, generated by
 * tools/gen_templates.py); they hold every static pixel of the price
 * tag *except* the big sale-price digits, which we draw on top in the
 * landscape rectangle defined by PRICETAG_PRICE_L* in templates.h.
 *
 * Layout reasoning is best read with templates.h side-by-side: the
 * template image is rotated 90° CCW for the panel (FPC on the right),
 * so we draw glyphs in landscape coordinates and translate to the
 * panel's 128x250 portrait framebuffer at blit time.
 */
#ifndef PRICETAG_RENDER_H
#define PRICETAG_RENDER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Composite template[idx] + price digits and refresh. price_str is an
 * ASCII string drawn in red, right-justified inside the price slot.
 * Returns 0 on success, -1 on bad index / unsupported character. */
int pricetag_render(int idx, const char *price_str);

#ifdef __cplusplus
}
#endif
#endif
