add_subdirectory(libc)
add_subdirectory(wireless)
add_subdirectory(3rdparty)
add_subdirectory(network)
add_subdirectory(sys)
add_subdirectory(os)

__component_add_subdirectory_ifdef(CONFIG_AI_SUPPORT ai)
add_subdirectory(boot)
__component_add_subdirectory_ifdef(CONFIG_COMPONENTS_SOFTCRC_ENABLE softcrc)
__component_add_subdirectory_ifdef(CONFIG_COMPONENTS_CMSIS_DAP_ENABLE cmsis_dap)
__component_add_subdirectory_ifdef(CONFIG_COMPONENTS_UTILITY_API_ENABLE utils)
__component_add_subdirectory_ifdef(CONFIG_COMPONENTS_SENSOR_ENABLE sensor)
if (CONFIG_IPRO7)
__component_add_subdirectory_ifdef(CONFIG_MM_SUPPORT isp_firmware)
__component_add_subdirectory_ifdef(CONFIG_MM_SUPPORT isp_algorithm)
__component_add_subdirectory_ifdef(CONFIG_MM_SUPPORT isp_iq_param)
__component_add_subdirectory_ifdef(CONFIG_MM_SUPPORT isp_iq_cmd)
endif()
__component_add_subdirectory_ifdef(CONFIG_FREERTOS_SUPPORT fs)
__component_add_subdirectory_ifdef(CONFIG_FREERTOS_SUPPORT crypto)
__component_add_subdirectory_ifdef(CONFIG_AT_CLIENT at_client)
__component_add_subdirectory_ifdef(CONFIG_COMPONENTS_CHERRYUSB_ENABLE cherryusb)
if (NOT CONFIG_BOOTROM)
add_subdirectory(audio)
endif()
__component_add_subdirectory_ifdef(CONFIG_UNIT_TEST_FRAMEWORK test)

# Shared utility components
add_subdirectory(json_utils)
